apiVersion: v1
kind: ServiceAccount
metadata:
  name: synology-csi-provisioner
  namespace: synology-csi
---
# Imported from external-provisioner v3.0.0
#
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: external-provisioner-runner
rules:
  - resources: ["persistentvolumes"]
    apiGroups: [""]
    verbs: ["get", "list", "watch", "create", "delete"]
  - resources: ["persistentvolumeclaims"]
    apiGroups: [""]
    verbs: ["get", "list", "watch", "update"]
  - resources: ["storageclasses"]
    apiGroups: ["storage.k8s.io"]
    verbs: ["get", "list", "watch"]
  - resources: ["events"]
    apiGroups: [""]
    verbs: ["list", "watch", "create", "update", "patch"]
  - resources: ["volumesnapshots"]
    apiGroups: ["snapshot.storage.k8s.io"]
    verbs: ["get", "list"]
  - resources: ["volumesnapshotcontents"]
    apiGroups: ["snapshot.storage.k8s.io"]
    verbs: ["get", "list"]
  - resources: ["csinodes"]
    apiGroups: ["storage.k8s.io"]
    verbs: ["get", "list", "watch"]
  - resources: ["nodes"]
    apiGroups: [""]
    verbs: ["get", "list", "watch"]
  - resources: ["volumeattachments"]
    apiGroups: ["storage.k8s.io"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: synology-csi-provisioner-role
roleRef:
  name: external-provisioner-runner
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
subjects:
  - name: synology-csi-provisioner
    namespace: synology-csi
    kind: ServiceAccount
---
# Imported from external-provisioner v3.0.0
#
# Provisioner must be able to work with endpoints in current namespace
# if (and only if) leadership election is enabled
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: external-provisioner-cfg
  namespace: synology-csi
rules:
  - resources: ["endpoints"]
    apiGroups: [""]
    verbs: ["get", "watch", "list", "delete", "update", "create"]
  - resources: ["leases"]
    apiGroups: ["coordination.k8s.io"]
    verbs: ["get", "watch", "list", "delete", "update", "create"]
  - resources: ["pods"]
    apiGroups: [""]
    verbs: ["get"]
  - resources: ["replicasets"]
    apiGroups: ["apps"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: synology-csi-provisioner-role-cfg
  namespace: synology-csi
roleRef:
  name: external-provisioner-cfg
  kind: Role
  apiGroup: rbac.authorization.k8s.io
subjects:
  - name: synology-csi-provisioner
    namespace: synology-csi
    kind: ServiceAccount
