# This YAML file contains all RBAC objects that are necessary to run external
# 
# Source is https://github.com/kubernetes-csi/external-resizer/blob/v1.2.0/deploy/kubernetes/rbac.yaml

apiVersion: v1
kind: ServiceAccount
metadata:
  name: synology-csi-resizer
  namespace: synology-csi
---
# Resizer must be able to work with PVCs, PVs, SCs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: external-resizer-runner
rules:
  - resources: ["persistentvolumes"]
    apiGroups: [""]
    verbs: ["get", "list", "watch", "patch"]
  - resources: ["persistentvolumeclaims"]
    apiGroups: [""]
    verbs: ["get", "list", "watch"]
  - resources: ["pods"]
    apiGroups: [""]
    verbs: ["get", "list", "watch"]
  - resources: ["persistentvolumeclaims/status"]
    apiGroups: [""]
    verbs: ["patch"]
  - resources: ["events"]
    apiGroups: [""]
    verbs: ["list", "watch", "create", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: synology-csi-resizer-role
roleRef:
  name: external-resizer-runner
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
subjects:
  - name: synology-csi-resizer
    namespace: synology-csi
    kind: ServiceAccount
---
# Resizer must be able to work with end point in current namespace
# if (and only if) leadership election is enabled
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: external-resizer-cfg
  namespace: synology-csi
rules:
  - resources: ["leases"]
    apiGroups: ["coordination.k8s.io"]
    verbs: ["get", "watch", "list", "delete", "update", "create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: synology-csi-resizer-role-cfg
  namespace: synology-csi
roleRef:
  name: external-resizer-cfg
  kind: Role
  apiGroup: rbac.authorization.k8s.io
subjects:
  - name: synology-csi-resizer
    namespace: synology-csi
    kind: ServiceAccount
