apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: synology-iscsi-storage
  namespace: synology-csi
  annotations:
    # set this to false if you do not want this storage class to be default
    storageclass.kubernetes.io/is-default-class: "true"
allowVolumeExpansion: true
provisioner: csi.synology.com
# uncomment below if you want to use different values than the default values
# parameters:
#   location: '/volume1'
#   type: 'BLUN'
reclaimPolicy: Retain
