apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Include base configuration
resources:
  - ../base

# Patch configuration with microk8s specific settings
patches:
  - path: node-patch.yaml
    target:
      kind: DaemonSet
      group: apps
      version: v1
